spring.application.name=crud

spring.datasource.url=jdbc:postgresql://localhost:5432/portal
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.context-path=/crud

jwt.secret=DJiINmjCboY830yZuqgr1pwtfGLnhQFMXk9xV24RvczlTdWAaHP5eEs6KUBO7S
# Access token - 15 menit
jwt.access-expiration=900000

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

app.base-url=http://localhost:8080/crud